=== Derovi/SwingShapesBackpack/src/main/resources/backpackSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.backpack.dero.by/">
    <xs:element name="backpack">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="shape" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="attribute">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                    <xs:attribute name="value" type="xs:int" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:int">
                                                <xs:minInclusive value="1"/>
                                                <xs:maxInclusive value="10000"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Cube"/>
                                    <xs:enumeration value="Sphere"/>
                                    <xs:enumeration value="Parallelepiped"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="size" type="xs:int"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Derovi/SwingShapesBackpack/src/main/resources/backpack.xml
<?xml version="1.0" encoding="UTF-8"?>
<backpack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="backpackSchema.xsd" size="18">
    <shape type = "Cube">
        <attribute name = "side" value = "228"/>
    </shape>
    <shape type = "Cube">
        <attribute name = "side" value = "15"/>
    </shape>
    <shape type = "Sphere">
        <attribute name = "radius" value = "10"/>
    </shape>
    <shape type = "Parallelepiped">
        <attribute name = "width" value = "12"/>
        <attribute name = "length" value = "6"/>
        <attribute name = "height" value = "14"/>
    </shape>
</backpack>
